language: java
jdk: openjdk8

branches:
  only:
  - master

before_script:
  - cd code/QuizHero_APP/

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  api_key:
    secure: LQpUF76lNmLmcBrE/mXtYFnblglF3cj5WZjC4XgDeMyxMccjJEMZaJDPpbzGyLfmOUcd6kPOXNorYmtL8eGTb/7NHwtPPFDmvCLhzY/JBlgyVkssvy5Pr6nKbPG5UkR/PxVI7AFzYJqPA/BbSvAul76Ff7WSqgRplpEbEVgT+g2Tk7zNgn2aWPJpqLFZJY6B4s0DMmljO/Uxrevbx97KHPFLEHSlA1QfZUrzMKosbhG7kut03fkE0355ghJcTnoi3NqOu43W0O8esUGW2Ny/020X+0HEZKaCBIzILDIdgtXvHToMvve0J/766ZE7aYQ8x3XcKqTpTr+vBECTTa1s6p3h7+dYosElAd55UH2zpDuDvp8e7qjqDGqAtuasNllJIhRaxBtJrJS57tND5/49ILB08thqi7d3kFG8uwBZO/MBSVHuThYEtEyuZ4cEYsz4wH5C4nYM3Sd+diuSzH6K5OqpGZfV2xOYkcoPuaWDARFI6iZ6OF25OwPkln/faqIoPq5o+L9+3cKnaOO8FtbhLRiVDienPqb2BKCKiprAGzp3BXsG2wxOtaD9fpISm2t47jaNGZUl9tRTlkYrAMpj1VijzaruySm89PUK4ksNyCa+XfC2X+42ISv88vLDFtl1C7MkFLg230lKWmpU1xyXLkFC+otd5pt8Bxmh1VZLHEE=
  app: quiz-hero
  skip_cleanup: true
